name: draggable_home
description: Draggable is a library for adding a beautiful draggable home page
version: 1.0.4
repository: https://github.com/4-alok/draggable_home
documentation: https://github.com/4-alok/draggable_home/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: null
